name: cashaam
description: Demo app for cashaam task of implementing auth

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: "^1.4.0"
  firebase_auth: "^3.0.1"
  cloud_firestore: "^2.4.0"
  flutter_bloc: ^8.0.1
  google_fonts: ^2.1.0
  hexcolor: ^2.0.6
  get_it: ^7.1.3
  sizer: ^2.0.13
  fluttertoast: ^8.0.8
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - 'assets/'